name       : secp256k1
version    : 2020.07.1097 # Use YEAR + MONTH + git rev-list --count HEAD
release    : 1
source     :
    - git|https://github.com/bitcoin-core/secp256k1.git : 3f4a5a10e43bfc8dae5b978cb39aa2dfbaf4d713
license    : MIT
optimize   : speed
component  : security.library
summary    : Optimized C library for ECDSA signatures and secret/public key operations on curve secp256k1.
description: |
    Optimized C library for ECDSA signatures and secret/public key operations on curve secp256k1.
setup      : |
    %autogen --disable-openssl-tests --disable-static --enable-module-recovery
build      : |
    %make
install    : |
    %make_install
